### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Oxidisedman** [SpamShield/PyroGramBot#1]
Hello, add some simple modules too

**Comment by MR-JINN-OF-TG** [comment]
> This is Just only a example bot bro. So I think no need of adding some modules on it.
May can create new sourcesand add features on it.

**Comment by Oxidisedman** [comment]
Well, skill is the most important factor..
If you trying add new things your skills will grow.
Cresting a bot is Not a simple experiment 😌😅

**Comment by MR-JINN-OF-TG** [comment]
👍
